version: '3'

services:
  db:
    build: ./docker/postgis
    image: postgis:9.6
    volumes:
        - .db:/var/lib/postgresql/data
    environment:
        - PGDATA=var/lib/postgresql/data/pgdata
  queue:
    image: rabbitmq
  web:
    build: .
    image: mspray:master
    volumes:
      - .:/srv/mspray
      - .data:/srv/data
      - .bash_history:/home/mspray/.bash_history
      - .inputrc:/home/mspray/.inputrc
    ports:
      - "8000:8000"
    depends_on:
      - db
      - queue
    environment:
       - DB_USER=mspray
       - DB_NAME=mspray
       - DB_PASS=mspray
       - DB_HOST=db
       - WORKON_HOME=.virtualenvs
